### ISSUE TITLE
Cannot correctly import user private key

### ISSUE THREAD

**Issue by sadeden** [blockades/poc_keybase_sign#1]
# Description

After fetching the private key using keybase api, the key format seems odd and thus the import fails.

# Steps to reproduce

- fill in your credentials
- wait for private key to be fetched and imported

# Observed behaviour

We get an error message saying : 

```
error Error: Unknown PKESK version: 98
    at PKESK_Parser.parse (/home/sadeden/Repos/git/poc_keybase_sign/node_modules/kbpgp/lib/openpgp/packet/sess.js:417:15)
    at Function.PKESK.parse (/home/sadeden/Repos/git/poc_keybase_sign/node_modules/kbpgp/lib/openpgp/packet/sess.js:34:40)
    at PacketParser.<anonymous> (/home/sadeden/Repos/git/poc_keybase_sign/node_modules/kbpgp/lib/openpgp/parser.js:86:26)
    at PacketParser.parse_body (/home/sadeden/Repos/git/poc_keybase_sign/node_modules/kbpgp/lib/openpgp/parser.js:120:10)
    at PacketParser.parse (/home/sadeden/Repos/git/poc_keybase_sign/node_modules/kbpgp/lib/openpgp/parser.js:74:18)
    at MessageParser.parse_packet (/home/sadeden/Repos/git/poc_keybase_sign/node_modules/kbpgp/lib/openpgp/parser.js:46:45)
    at MessageParser.parse (/home/sadeden/Repos/git/poc_keybase_sign/node_modules/kbpgp/lib/openpgp/parser.js:40:28)
    at /home/sadeden/Repos/git/poc_keybase_sign/node_modules/kbpgp/lib/openpgp/parser.js:191:57
    at Object.katch (/home/sadeden/Repos/git/poc_keybase_sign/node_modules/pgp-utils/lib/util.js:210:13)
    at parse (/home/sadeden/Repos/git/poc_keybase_sign/node_modules/kbpgp/lib/openpgp/parser.js:190:17)
```

# Expected behaviour:

We should see a message saying : `Loaded private key with passphrase`

**Comment by sadeden** [comment]
See https://github.com/blockades/poc_keybase_sign/commit/6858986ee883120b376f039f7d4c820406329cdd
